"""Lossless MLIR syntax and mutable semantic documents backed by Zirium."""

from importlib.metadata import version as _distribution_version

from ._zirium import (  # ty: ignore[unresolved-import]
    AttributeSpecHandle,
    Diagnostic,
    DialectRegistry,
    Document,
    File,
    ForeignHandleError,
    LoweringResult,
    Operation,
    OperationShape,
    OperationSpec,
    OperationTable,
    ResourceLimitError,
    SemanticAttribute,
    SemanticBlock,
    SemanticDiagnostic,
    SemanticEdit,
    SemanticEditError,
    SemanticOperation,
    SemanticRegion,
    SemanticStatistics,
    SemanticType,
    SemanticUse,
    SemanticValue,
    SemanticVerificationError,
    StaleHandleError,
    StructuralVerificationError,
    SyntaxNode,
    SyntaxOperationTable,
    SyntaxTable,
    Token,
    parse_bytes,
    parse_file,
    parse_text,
)
from .config import OperationShapeConfig, RegistryConfig

__version__ = _distribution_version("zirium")

__all__ = [
    "AttributeSpecHandle",
    "Diagnostic",
    "DialectRegistry",
    "Document",
    "File",
    "ForeignHandleError",
    "LoweringResult",
    "Operation",
    "OperationShape",
    "OperationShapeConfig",
    "OperationSpec",
    "OperationTable",
    "RegistryConfig",
    "ResourceLimitError",
    "SemanticAttribute",
    "SemanticBlock",
    "SemanticDiagnostic",
    "SemanticEdit",
    "SemanticEditError",
    "SemanticOperation",
    "SemanticRegion",
    "SemanticStatistics",
    "SemanticType",
    "SemanticUse",
    "SemanticValue",
    "SemanticVerificationError",
    "StaleHandleError",
    "StructuralVerificationError",
    "SyntaxNode",
    "SyntaxOperationTable",
    "SyntaxTable",
    "Token",
    "__version__",
    "parse_bytes",
    "parse_file",
    "parse_text",
]
