"""Lossless MLIR syntax and mutable semantic documents backed by Zirium."""

from collections.abc import Mapping
from os import PathLike
from types import TracebackType
from typing import Literal, Self, TypeAlias

_TextRange: TypeAlias = tuple[int, int]
_Path: TypeAlias = str | PathLike[str]
_Retention: TypeAlias = Literal[
    "semantic", "semantic_only", "syntax", "syntax_only", "hybrid"
]
_DeclarativeOperation: TypeAlias = Literal[
    "builtin.module",
    "func.func",
    "func.return",
    "func.call",
    "arith.constant",
    "arith.addi",
    "cf.br",
    "cf.cond_br",
]

class StaleHandleError(Exception): ...
class ForeignHandleError(Exception): ...
class SemanticEditError(Exception): ...
class StructuralVerificationError(Exception): ...
class SemanticVerificationError(Exception): ...

class Diagnostic:
    @property
    def kind(self) -> str: ...
    @property
    def range(self) -> _TextRange: ...

class OperationShape:
    FUNC_LIKE: OperationShape
    CALL_LIKE: OperationShape

class DialectRegistry:
    """Dialect syntax and semantic rules retained through parse and lower."""

    @staticmethod
    def empty() -> DialectRegistry: ...
    @staticmethod
    def core() -> DialectRegistry: ...
    @staticmethod
    def proving() -> DialectRegistry: ...
    @staticmethod
    def declarative(operations: list[_DeclarativeOperation]) -> DialectRegistry: ...
    @staticmethod
    def with_operation_shapes(
        operation_shapes: Mapping[str, OperationShape],
    ) -> DialectRegistry: ...

class SyntaxNode:
    @property
    def kind(self) -> str: ...
    @property
    def range(self) -> _TextRange | None: ...
    @property
    def has_error(self) -> bool: ...
    def child_indices(self) -> bytes: ...
    def descendant_range(self) -> tuple[int, int]: ...
    def token_range(self) -> tuple[int, int]: ...
    def text(self) -> bytes: ...
    def as_operation(self) -> Operation | None: ...

class Token:
    @property
    def kind(self) -> str: ...
    @property
    def range(self) -> _TextRange: ...
    def text(self) -> bytes: ...

class SyntaxTable:
    """Packed native-endian columns whose indexes and kind codes belong to one source File."""
    @property
    def node_kind(self) -> bytes: ...
    @property
    def node_start(self) -> bytes: ...
    @property
    def node_end(self) -> bytes: ...
    @property
    def node_subtree_end(self) -> bytes: ...
    @property
    def node_flags(self) -> bytes: ...
    @property
    def token_kind(self) -> bytes: ...
    @property
    def token_start(self) -> bytes: ...
    @property
    def token_end(self) -> bytes: ...
    @staticmethod
    def node_kind_code(name: str) -> int: ...
    @staticmethod
    def node_kind_name(code: int) -> str: ...
    @staticmethod
    def token_kind_code(name: str) -> int: ...
    @staticmethod
    def token_kind_name(code: int) -> str: ...

class Operation:
    @property
    def range(self) -> _TextRange | None: ...
    @property
    def has_error(self) -> bool: ...
    def syntax(self) -> SyntaxNode: ...
    def text(self) -> bytes: ...
    def properties(self) -> SyntaxNode | None: ...
    def attributes(self) -> SyntaxNode | None: ...
    def trailing_location(self) -> SyntaxNode | None: ...

class SyntaxOperationTable:
    @property
    def operation_node(self) -> bytes: ...
    @property
    def result_offsets(self) -> bytes: ...
    @property
    def result_nodes(self) -> bytes: ...
    @property
    def operand_offsets(self) -> bytes: ...
    @property
    def operand_nodes(self) -> bytes: ...
    @property
    def successor_offsets(self) -> bytes: ...
    @property
    def successor_nodes(self) -> bytes: ...
    @property
    def region_offsets(self) -> bytes: ...
    @property
    def region_nodes(self) -> bytes: ...

class File:
    """Owning lossless parse result with syntax diagnostics and lowering entry points."""

    @property
    def root(self) -> SyntaxNode: ...
    @property
    def diagnostics(self) -> list[Diagnostic]: ...
    def original_bytes(self) -> bytes: ...
    def write_original(self, path: _Path) -> None: ...
    @property
    def node_count(self) -> int: ...
    @property
    def token_count(self) -> int: ...
    def node(self, index: int) -> SyntaxNode: ...
    def token(self, index: int) -> Token: ...
    def syntax_table(self) -> SyntaxTable: ...
    @property
    def operation_count(self) -> int: ...
    def operation(self, index: int) -> Operation: ...
    def operation_table(self) -> SyntaxOperationTable: ...
    def lower_strict(self, retention: _Retention | None = None) -> LoweringResult: ...
    def lower_best_effort(
        self, retention: _Retention | None = None
    ) -> LoweringResult: ...

class LoweringResult:
    @property
    def document(self) -> Document | None: ...
    @property
    def diagnostics(self) -> list[SemanticDiagnostic]: ...
    @property
    def semantically_complete(self) -> bool: ...

class SemanticDiagnostic:
    @property
    def range(self) -> _TextRange: ...
    @property
    def message(self) -> str: ...

class SemanticStatistics:
    @property
    def operations(self) -> int: ...
    @property
    def regions(self) -> int: ...
    @property
    def blocks(self) -> int: ...
    @property
    def local_types(self) -> int: ...
    @property
    def local_attributes(self) -> int: ...
    @property
    def payload_blobs(self) -> int: ...
    @property
    def payload_blob_bytes(self) -> int: ...
    @property
    def retained_source_bytes(self) -> int: ...
    @property
    def direct_owned_bytes(self) -> int: ...
    @property
    def document_index_bytes(self) -> int: ...
    @property
    def retained_cst_bytes(self) -> int: ...
    @property
    def source_storage_shared(self) -> bool: ...
    @property
    def cst_storage_shared(self) -> bool: ...
    @property
    def pooled_list_entries(self) -> int: ...
    @property
    def use_index_entries(self) -> int: ...
    @property
    def symbol_index_entries(self) -> int: ...
    @property
    def dominance_index_entries(self) -> int: ...

class OperationTable:
    @property
    def revision(self) -> int: ...
    @property
    def name_code(self) -> bytes: ...
    @property
    def source_start(self) -> bytes: ...
    @property
    def source_end(self) -> bytes: ...
    @property
    def root_flags(self) -> bytes: ...
    @property
    def name_offsets(self) -> bytes: ...
    @property
    def name_bytes(self) -> bytes: ...
    @property
    def count(self) -> int: ...
    def operation(self, index: int) -> SemanticOperation: ...

class Document:
    """Mutable semantic document with generation-checked handles and atomic edits."""

    @property
    def semantically_complete(self) -> bool: ...
    @property
    def retention(self) -> Literal["semantic", "syntax", "hybrid"]: ...
    @property
    def diagnostics(self) -> list[SemanticDiagnostic]: ...
    def operation_table(self, name: str | None = None) -> OperationTable: ...
    def statistics(self) -> SemanticStatistics: ...
    def edit(self) -> SemanticEdit: ...
    def uses(self, value: SemanticValue) -> list[SemanticUse]: ...
    def lookup_symbol(
        self, from_operation: SemanticOperation, symbol: str
    ) -> SemanticOperation | None: ...
    def symbol_diagnostics(self) -> list[tuple[SemanticOperation, str]]: ...
    def dominates(self, value: SemanticValue, operation: SemanticOperation) -> bool: ...
    def validate_structure(self) -> None: ...
    def verify_semantics(self) -> None: ...
    def canonical_bytes(self, compact: bool = False) -> bytes: ...
    def write_canonical(self, path: _Path, compact: bool = False) -> None: ...
    def custom_bytes(self, compact: bool = False) -> bytes: ...
    def write_custom(self, path: _Path, compact: bool = False) -> None: ...
    def preserving_bytes(self, compact: bool = False) -> bytes: ...
    def write_preserving(self, path: _Path, compact: bool = False) -> None: ...
    def structurally_equal(self, other: Document) -> bool: ...

class AttributeSpecHandle:
    def __init__(
        self, attribute: SemanticAttribute, name: str | None = None
    ) -> None: ...
    @property
    def name(self) -> str: ...

class OperationSpec:
    def __init__(
        self,
        name: str,
        operands: list[SemanticValue],
        result_types: list[SemanticType],
        function_type: SemanticType,
        attributes: list[AttributeSpecHandle] = [],
        properties: list[AttributeSpecHandle] = [],
    ) -> None: ...

class SemanticEdit:
    """Buffered transaction that commits when its context exits normally."""

    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool: ...
    def insert_root(self, index: int, spec: OperationSpec) -> None: ...
    def insert(self, block: SemanticBlock, index: int, spec: OperationSpec) -> None: ...
    def erase(self, operation: SemanticOperation) -> None: ...
    def rewire_operand(
        self, operation: SemanticOperation, index: int, value: SemanticValue
    ) -> None: ...
    def rewire_successor_argument(
        self,
        operation: SemanticOperation,
        successor: int,
        argument: int,
        value: SemanticValue,
    ) -> None: ...
    def replace_result_types(
        self, operation: SemanticOperation, types: list[SemanticType]
    ) -> None: ...
    def set_attribute(
        self, operation: SemanticOperation, value: AttributeSpecHandle
    ) -> None: ...
    def remove_attribute(self, operation: SemanticOperation, name: str) -> None: ...
    def set_property(
        self, operation: SemanticOperation, value: AttributeSpecHandle
    ) -> None: ...
    def remove_property(self, operation: SemanticOperation, name: str) -> None: ...
    def replace_all_uses(self, from_: SemanticValue, to: SemanticValue) -> None: ...
    def compact_pools(self) -> None: ...

class SemanticUse:
    @property
    def kind(self) -> Literal["operand", "successor_argument"]: ...
    @property
    def operation(self) -> SemanticOperation: ...
    @property
    def index(self) -> int: ...
    @property
    def successor(self) -> int | None: ...

class SemanticOperation:
    @property
    def mnemonic(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def source_range(self) -> _TextRange | None: ...
    @property
    def is_unparsed(self) -> bool: ...
    @property
    def unparsed_text(self) -> bytes | None: ...
    def region_count(self) -> int: ...
    def region(self, index: int) -> SemanticRegion: ...
    def operand_count(self) -> int: ...
    def operand(self, index: int) -> SemanticValue: ...
    def result_count(self) -> int: ...
    def result(self, index: int) -> SemanticValue: ...
    def result_type(self, index: int) -> SemanticType: ...
    def attribute_count(self) -> int: ...
    def attribute(self, index: int) -> SemanticAttribute: ...
    def attribute_by_name(self, name: str) -> SemanticAttribute | None: ...
    def attribute_snapshot(self) -> list[tuple[str, str]]: ...
    def property_snapshot(self) -> list[tuple[str, str]]: ...

class SemanticRegion:
    def block_count(self) -> int: ...
    def block(self, index: int) -> SemanticBlock: ...
    def parent_operation(self) -> SemanticOperation: ...

class SemanticBlock:
    @property
    def label(self) -> str | None: ...
    def operation_count(self) -> int: ...
    def operation(self, index: int) -> SemanticOperation: ...
    def argument_count(self) -> int: ...
    def argument(self, index: int) -> SemanticValue: ...
    def parent_region(self) -> SemanticRegion: ...

class SemanticValue:
    @property
    def valid(self) -> bool: ...
    @property
    def kind(self) -> Literal["operation_result", "block_argument", "invalid"]: ...
    @property
    def key(self) -> int | None: ...
    @property
    def defining_operation(self) -> SemanticOperation | None: ...
    @property
    def type_value(self) -> SemanticType | None: ...

class SemanticType:
    @property
    def spelling(self) -> str: ...
    @property
    def kind(
        self,
    ) -> Literal[
        "integer",
        "float",
        "index",
        "tuple",
        "tensor",
        "vector",
        "memref",
        "function",
        "opaque",
        "invalid",
    ]: ...

class SemanticAttribute:
    @property
    def name(self) -> str: ...
    @property
    def kind(
        self,
    ) -> Literal[
        "dense",
        "sparse",
        "resource",
        "boolean",
        "integer",
        "float",
        "string",
        "type",
        "symbol",
        "array",
        "dictionary",
        "location",
        "affine_map",
        "integer_set",
        "wide_number",
        "opaque",
        "invalid",
    ]: ...
    @property
    def spelling(self) -> str: ...
    @property
    def string_value(self) -> str | None: ...
    @property
    def integer_value(self) -> int | None: ...
    @property
    def float_value(self) -> float | None: ...
    @property
    def boolean_value(self) -> bool | None: ...
    @property
    def symbol_value(self) -> str | None: ...
    @property
    def payload_byte_length(self) -> int | None: ...
    def raw_buffer(self) -> bytes | None: ...

class ResourceLimitError(Exception): ...

def parse_bytes(
    data: bytes,
    *,
    registry: DialectRegistry | None = None,
    max_file_bytes: int | None = None,
    max_tokens: int | None = None,
    max_delimiter_depth: int | None = None,
    max_payload_bytes: int | None = None,
    max_numeric_literal_bytes: int | None = None,
    max_attribute_depth: int | None = None,
    max_alias_expansion_depth: int | None = None,
) -> File: ...
def parse_text(
    text: str,
    *,
    registry: DialectRegistry | None = None,
    max_file_bytes: int | None = None,
    max_tokens: int | None = None,
    max_delimiter_depth: int | None = None,
    max_payload_bytes: int | None = None,
    max_numeric_literal_bytes: int | None = None,
    max_attribute_depth: int | None = None,
    max_alias_expansion_depth: int | None = None,
) -> File: ...
def parse_file(
    path: _Path,
    *,
    registry: DialectRegistry | None = None,
    max_file_bytes: int | None = None,
    max_tokens: int | None = None,
    max_delimiter_depth: int | None = None,
    max_payload_bytes: int | None = None,
    max_numeric_literal_bytes: int | None = None,
    max_attribute_depth: int | None = None,
    max_alias_expansion_depth: int | None = None,
) -> File: ...
