"""Typed structured query builders; expression construction does no document work."""

from typing import Generic, Literal, Never, Self, TypeVar

from . import Change, SemanticAttribute, SemanticOperation, SemanticType

_T = TypeVar("_T")

class QueryExpr(Generic[_T]):
    def __bool__(self) -> Never: ...

class Predicate:
    def __and__(self, other: Predicate) -> Predicate: ...
    def __or__(self, other: Predicate) -> Predicate: ...
    def __invert__(self) -> Predicate: ...
    def __bool__(self) -> Never: ...

class ChangePredicate:
    def __and__(self, other: ChangePredicate | Predicate) -> ChangePredicate: ...
    def __or__(self, other: ChangePredicate | Predicate) -> ChangePredicate: ...
    def __invert__(self) -> ChangePredicate: ...
    def __bool__(self) -> Never: ...

class ChangeQuery(QueryExpr[list[Change]]):
    def filter(self, predicate: ChangePredicate | Predicate) -> ChangeQuery: ...
    def before(self) -> DiffOpQuery: ...
    def after(self) -> DiffOpQuery: ...
    def unique(self) -> ChangeQuery: ...
    def names(self) -> DiffStringQuery: ...
    def count(self) -> DiffCountQuery: ...

class DiffOpQuery(QueryExpr[list[SemanticOperation]]):
    def filter(self, predicate: Predicate) -> DiffOpQuery: ...
    def users(self, index: int | None = None) -> DiffOpQuery: ...
    def defs(self, index: int | None = None) -> DiffOpQuery: ...
    def unique(self) -> DiffOpQuery: ...
    def names(self) -> DiffStringQuery: ...
    def count(self) -> DiffCountQuery: ...

class DiffStringQuery(QueryExpr[list[str]]):
    def unique(self) -> DiffStringQuery: ...
    def count(self) -> DiffCountQuery: ...

class DiffCountQuery(QueryExpr[int]): ...

class OpQuery(QueryExpr[list[SemanticOperation]]):
    def unique(self) -> Self: ...
    def reverse(self) -> Self: ...
    def count(self) -> CountQuery: ...
    def head(self, count: int) -> Self: ...
    def tail(self, count: int) -> Self: ...
    def parent(self) -> OpQuery: ...
    def children(self) -> OpQuery: ...
    def subtree(self) -> OpQuery: ...
    def closure(self) -> OpQuery: ...
    def slice(self) -> OpQuery:
        """Follow transitive SSA definitions; evaluation terminates on cycles."""
    def reachable(self) -> OpQuery: ...
    def filter(self, predicate: Predicate) -> OpQuery: ...
    def root(self, predicate: Predicate) -> OpQuery: ...
    def defs(self, index: int | None = None) -> OpQuery: ...
    def users(self, index: int | None = None) -> OpQuery: ...
    def where_exists(self, query: OpQuery) -> OpQuery: ...
    def fixpoint(self, query: OpQuery) -> OpQuery: ...
    def sort_by(self, key: ScalarStringQuery | CountQuery) -> OpQuery: ...
    def min_by(self, key: ScalarStringQuery | CountQuery) -> OpQuery: ...
    def max_by(self, key: ScalarStringQuery | CountQuery) -> OpQuery: ...
    def min_all_by(self, key: ScalarStringQuery | CountQuery) -> OpQuery: ...
    def max_all_by(self, key: ScalarStringQuery | CountQuery) -> OpQuery: ...
    def map_by(self, key: ScalarStringQuery, value: QueryExpr[_T]) -> MapQuery[_T]: ...
    def names(self) -> StringQuery: ...
    def string_attr(self, name: str) -> StringQuery: ...
    def attributes(self, name: str) -> AttributeQuery: ...
    def result_types(self) -> TypeQuery: ...
    def operand_types(self) -> TypeQuery: ...
    def union(self, other: Self) -> Self: ...
    def intersect(self, other: Self) -> Self: ...
    def difference(self, other: Self) -> Self: ...

class StringQuery(QueryExpr[list[str]]):
    def unique(self) -> Self: ...
    def reverse(self) -> Self: ...
    def count(self) -> CountQuery: ...
    def head(self, count: int) -> Self: ...
    def tail(self, count: int) -> Self: ...
    def union(self, other: Self) -> Self: ...
    def intersect(self, other: Self) -> Self: ...
    def difference(self, other: Self) -> Self: ...
    def sort(self) -> StringQuery: ...
    def min(self) -> StringQuery: ...
    def max(self) -> StringQuery: ...
    def min_all(self) -> StringQuery: ...
    def max_all(self) -> StringQuery: ...
    def one(self) -> ScalarStringQuery: ...
    def tally(self) -> MapQuery[int]: ...

class CountQuery(QueryExpr[int]): ...
class ScalarStringQuery(QueryExpr[str]): ...

class TypeQuery(QueryExpr[list[SemanticType]]):
    def unique(self) -> Self: ...
    def reverse(self) -> Self: ...
    def count(self) -> CountQuery: ...
    def head(self, count: int) -> Self: ...
    def tail(self, count: int) -> Self: ...
    def spellings(self) -> StringQuery: ...

class AttributeQuery(QueryExpr[list[SemanticAttribute]]):
    def unique(self) -> Self: ...
    def reverse(self) -> Self: ...
    def count(self) -> CountQuery: ...
    def head(self, count: int) -> Self: ...
    def tail(self, count: int) -> Self: ...
    def spellings(self) -> StringQuery: ...

class MapQuery(QueryExpr[dict[str, _T]]):
    def count(self) -> CountQuery: ...

def ops() -> OpQuery: ...
def input() -> OpQuery: ...
def op(name: str) -> Predicate: ...
def dialect(name: str) -> Predicate: ...
def has_attr(name: str) -> Predicate: ...
def result_type(spelling: str) -> Predicate: ...
def string_attr_eq(name: str, value: str) -> Predicate: ...
def always(value: bool) -> Predicate: ...
def changes() -> ChangeQuery: ...
def change(
    kind: Literal["added", "removed", "modified", "moved"],
) -> ChangePredicate: ...
def changed(
    field: Literal[
        "name",
        "operands",
        "result_types",
        "function_type",
        "attributes",
        "properties",
        "successors",
        "regions",
        "location",
        "position",
    ],
) -> ChangePredicate: ...
